


// create new product
POST http://localhost:6969/api/products/
Content-Type: application/json

{
  "title": "Test",
    "description": "Printed midi chiffon skirt with a gently pleated finish. Concealed zipper at the side. Length of skirt: 83.5cm / 33.3",
    "category": ["test"],
    "quantity": 10,
    "price": 429,
    "img": "https://github.com/msmalinosterberg/miniprojekt/blob/master/src/assets/prod8.png?raw=true"
}

###


// GET all products
GET http://localhost:6969/api/products/

###



// DELETE product
DELETE  http://localhost:6969/api/products/60a3b917a8a280045c36428a

###


// EDIT product
PUT http://localhost:6969/api/products/60a50c1dd2f3e72e9c2eabdd
Content-Type: application/json

{
    "quantity": 1337
}
###
