
GET http://localhost:6969/api/shipping

###

POST http://localhost:6969/api/shipping
Content-Type: application/json

{
    "shipmentCompany": "Schenker",
    "deliveryTime": 72,
    "shippingPrice": 89
}


###

DELETE http://localhost:6969/api/shipping/60a4dc77b25b35c0ebe1f5c7

###

PUT http://localhost:6969/api/shipping/60a60fbca48250da587ab64a
Content-Type: application/json

{
    "shipmentCompany": "Schenker",
    "deliveryTime": ,
    "shippingPrice": 89
}
