POST http://localhost:6969/api/upload
Content-Type: multipart/form-data; boundary=Row

--Row
Content-Disposition: form-data; name="img"; filename="chillDog.jpg"
Content-Type: image/jpeg

./chillDog.jpg
--Row--


###

GET http://localhost:6969/uploads/1621842021641-dance.jpg