// create new product
POST http://localhost:6969/api/order/
Content-Type: application/json

{
  "date": "test22s3",
  "isHandled": false,
  "product": ["60a4ea4a5f28755b848c1eca", 2],
  "user": "1",
  "shipping": "postnord"
}

###


// GET all products
GET http://localhost:6969/api/products/

###



// DELETE product
DELETE  http://localhost:6969/api/products/60a3b917a8a280045c36428a

###


// EDIT product
PUT http://localhost:6969/api/products/60a3be97372119312c306bca
Content-Type: application/json

{
    "quantity": 1337
}
###