// create new product
POST http://localhost:6969/api/order/
Content-Type: application/json

{
  "date": "01-02-2021",
  "isHandled": false,
  "product": [{ "id": "60a4ea4a5f28755b848c1eca","quantity": 2}],
  "user": "60a4b9329a4b2a1748f8ea1c",
  "shipping": "postnord"
}

###


// GET all orders
GET http://localhost:6969/api/order/

###



// DELETE product
DELETE  http://localhost:6969/api/products/60a3b917a8a280045c36428a

###


// EDIT product
PUT http://localhost:6969/api/products/60a3be97372119312c306bca
Content-Type: application/json

{
    "quantity": 1337
}
###