// GET all products
GET http://localhost:6969/api/accounts/

###
// GET specific account
GET http://localhost:6969/api/accounts/60a4b9339a4b2a1748f8ea1c

###



// create new product
POST http://localhost:6969/api/accounts/
Content-Type: application/json

{
    "userName": "1s23",
    "role": "123",
    "password": "123"
}
###


// DELETE product
DELETE  http://localhost:6969/api/accounts/60a4b9549a4b2a1748f8ea1d

###


// EDIT product
PUT http://localhost:6969/api/accounts/60a4b9f99a4b2a1748f8ea1e
Content-Type: application/json

{
    "userName": "BigBoy",
    "role": "admin",
    "password" : "123"
}
###