// GET all products
GET http://localhost:6969/api/accounts/

###
// GET specific account
GET http://localhost:6969/api/accounts/60acf07c035ae53978fe9987

###



// create new product
POST http://localhost:6969/api/accounts/
Content-Type: application/json

{
    "userName": "test",
    "fullName": "Testr Testrsson",
    "password": "test",
    "email" : "elon_musk@pornhub.com",
    "phoneNumber" : "0706969420",
    "address" : {
        "street": "Gatan 123",
        "zipCode": 42069,
        "city": "Cooltown",
        "country": "Narnia"
    }
}
###


// DELETE product
DELETE  http://localhost:6969/api/accounts/60accbc52870f52c8cad3a32
###


// EDIT product
PUT http://localhost:6969/api/accounts/60acf07c035ae53978fe9987
Content-Type: application/json

{
    "userName": "123",
    "role" : "admin",
    "email" : "elon_musk@pornhub.com",
    "phoneNumber" : "0706969420",
    "address" : {
         "street": "Gatan 123",
        "zipCode": 42069,
        "city": "Cooltown",
        "country": "Narnsssia"
    }
}
###

// update password from id
PATCH http://localhost:6969/api/accounts/60b4e1cdcc34fa445889db05
Content-Type: application/json

{
    "password": "test"
}