// create new product
POST http://localhost:6969/api/login/
Content-Type: application/json

{
  "userName": "123",
  "password":  "1223"
}


###
DELETE http://localhost:6969/api/logout


###

GET http://localhost:6969/api/authenticated/

