// create new product
POST http://localhost:6969/api/login/
Content-Type: application/json

{
  "userName": "1s23",
  "password":  "123"
}


###
DELETE http://localhost:6969/api/logout


###

GET http://localhost:6969/api/authenticated/

