// create new product
POST http://localhost:6969/api/login/
Content-Type: application/json

{
  "username": "TestUser",
  "password":  "1234"
}

###

POST http://localhost:6969/api/guest/
Content-Type: application/json

{
  "username": "guest"
}

###
DELETE http://localhost:6969/api/logout
